=== btblog/VoodooShader/Server/Xml/ConfigManifest.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="Uuid">
        <xs:restriction base="xs:string">
            <xs:pattern
                value="[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}">
            </xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="NamedString">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:element name="VoodooConfig">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Global">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="Variables" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Variable" maxOccurs="unbounded" type="NamedString" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Plugins" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="File"  minOccurs="0" maxOccurs="unbounded" type="xs:string" />
                                        <xs:element name="Path"  minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="filter" type="xs:string" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>                                        
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>                                
                            </xs:element>
                            <xs:element name="Classes">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="Adapter" type="xs:string" />
                                        <xs:element name="FileSystem" type="xs:string" />
                                        <xs:element name="HookManager" type="xs:string" />
                                        <xs:element name="Logger" type="xs:string" />
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Classes" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Class" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:any maxOccurs="unbounded" processContents="lax" />
                                    </xs:sequence>
                                    <xs:attribute name="name" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== btblog/VoodooShader/Server/Xml/example/ExampleConfig.xml
<?xml version="1.0" encoding="utf-8"?>
<VoodooConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://www.voodooshader.com/manifests/ConfigManifest.xsd">
    <Global>
        <Variables>
            <Variable name="adapter">VSAdapter</Variable>
        </Variables>
        <Plugins>
            <File>Voodoo_Core.dll</File>
        </Plugins>
        <Classes>
            <Adapter>$(adapter)</Adapter>
            <FileSystem>VSFileSystem</FileSystem>
            <HookManager>VSHookManager</HookManager>
            <Logger>VSLogger</Logger>
        </Classes>
    </Global>
    <Classes>
        <Class name="VSCore">
            <Tag id="unknown" />
        </Class>
    </Classes>
</VoodooConfig>
