=== btblog/VoodooShader/Server/Xml/RemoteManifest.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="Uuid">
        <xs:restriction base="xs:string">
            <xs:pattern
                value="[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}">
            </xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="VoodooManifest">
        <xs:complexType>
            <xs:all>
                <xs:element name="Packages">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="Package">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="Name" type="xs:string" />
                                        <xs:element name="PackID" type="Uuid" />
                                        <xs:element name="Version" type="xs:string" />
                                        <xs:element name="Date" type="xs:date" />
                                        <xs:element name="Manifest" type="xs:string" />
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Modules">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="Module">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="Name" type="xs:string" />
                                        <xs:element name="LibID" type="Uuid" />
                                        <xs:element name="PackID" type="Uuid" />
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Classes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="Class">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="Name" type="xs:string" />
                                        <xs:element name="ClsID" type="Uuid" />
                                        <xs:element name="LibID" type="Uuid" />
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
            <xs:attribute name="type" type="xs:string" use="required" />
            <xs:attribute name="name" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== btblog/VoodooShader/Server/Xml/ExampleRemoteManifest.xml
<?xml version="1.0" encoding="utf-8"?>
<VoodooManifest type="remote" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.voodooshader.com/manifests/RemoteManifest.xsd">
    <Packages>
        <Package>
            <Name>Package 1 Name</Name>
            <PackID>01234567-0123-0123-0123-0123456789AB</PackID>
            <Version>Version String</Version>
            <Date>2011-01-11</Date>
            <ManifestUri>http://test/manifests/Package1.xml</ManifestUri>        
        </Package>
        <Package>
            <Name>Package 2 Name</Name>
            <PackID>01234567-0123-0123-0123-0123456789AC</PackID>
            <Version>Version String</Version>
            <Date>2011-01-13</Date>
            <ManifestUri>http://test/manifests/Package2.xml</ManifestUri>
        </Package>
    </Packages>
    <Modules>
        <Module>
            <Name>Module 1</Name>
            <LibID>01234567-0123-0123-0123-0123456789AD</LibID>
            <PackID>01234567-0123-0123-0123-0123456789AC</PackID>
        </Module>
        <Module>
            <Name>Module 2</Name>
            <LibID>01234567-0123-0123-0123-0123456789AE</LibID>
            <PackID>01234567-0123-0123-0123-0123456789AB</PackID>
        </Module>
    </Modules>
    <Classes>
        <Class>
            <Name>Class 1</Name>
            <ClsID>01234567-0123-0123-0123-0123456789BE</ClsID>
            <LibID>01234567-0123-0123-0123-0123456789AD</LibID>
        </Class>
        <Class>
            <Name>Class 2</Name>
            <ClsID>01234567-0123-0123-0123-0123456789BB</ClsID>
            <LibID>01234567-0123-0123-0123-0123456789AE</LibID>          
        </Class>
    </Classes>
</VoodooManifest>

=== btblog/VoodooShader/Server/Xml/example/ExampleRemoteManifest.xml
<?xml version="1.0" encoding="utf-8"?>
<VoodooManifest type="remote" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.voodooshader.com/manifests/RemoteManifest.xsd">
    <Packages>
        <Package>
            <Name>Package 1 Name</Name>
            <PackID>01234567-0123-0123-0123-0123456789AB</PackID>
            <Version>Version String</Version>
            <Date>2011-01-11</Date>
            <ManifestUri>http://test/manifests/Package1.xml</ManifestUri>
        </Package>
        <Package>
            <Name>Package 2 Name</Name>
            <PackID>01234567-0123-0123-0123-0123456789AC</PackID>
            <Version>Version String</Version>
            <Date>2011-01-13</Date>
            <ManifestUri>http://test/manifests/Package2.xml</ManifestUri>
        </Package>
    </Packages>
</VoodooManifest>
